name: first workflow
on: workflow_dispatch

jobs:
  first:
    runs-on: ubuntu-latest

    steps:
      - name: print greeting
        run: |
            echo "Hello World"
            echo "Second shout"

      - name: print goodbye
        run: echo "Done, bye"
